### ISSUE TITLE
Mutable collection classes should not implement their immutable counterparts

### ISSUE THREAD

**Issue by mhmdanas** [passsy/kt.dart#119]
Example of why I think this is bad behavior:
```dart
final mutableList = mutableListOf(1, 2, 3);
final KtList<int> immutableList = mutableList;
mutableList[0] = 0;
print(immutableList); // Prints [0, 2, 3]!
```
I think this breaks the expectation that immutable collections should never change, which might cause some bugs.

I'd be happy to open a PR, although I imagine such a large breaking change would require a new major version.

**Comment by passsy** [comment]
## Working as intended

This is working as intended given that the same Kotlin code gives the same results

```kotlin
val mutableList = mutableListOf(1, 2, 3);
val immutableList: List<Int> = mutableList;
mutableList[0] = 0;
println(immutableList); // Prints [0, 2, 3]!
```

When exposing a `KtList` in an API it is immutable to the consumer, but might be backed by a mutable collection internally.

## Darts limitation

The idea that the content of a `KtList` never changes can't be enforced with an interface. The implementation decides the behaviour and a `mutableList` doesn't follow the immutable principle.

Being truly immutable is impossible with dart because 1. classes can't be `final` and can always be extended and 2. every class is its own interface and can be implemented.

Even if `KtMutableList` wouldn't implement `KtList` the same problem could occur if someone implements their own `KtList`.

```dart
/// A custom KtList implementation which doesn't follow the immutable principle
/// Evil but does the job 🤷‍♂ 
class MyKtList<T> implements KtList<T> {
  // copy KtList impl

  // add add your own mutation methods
  void replaceFirst(T) {
    // ...
  }
}

final myList = MyKtList(1, 2, 3);
// upcast from MyKtList to KtList possible
final KtList<int> immutableList = myList; 
mutableList.repalceFirst(0);
print(immutableList); // Prints [0, 2, 3]!
```

## The workaround

If you see someone doing an upcast it is up to reviewer to point out that the mutable collection should be converted to a real immutable **implementation** before exposing. This prevents users to cast to the mutable implementation themselves and do evil things.

```diff
final mutableList = mutableListOf(1, 2, 3);
-final KtList<int> immutableList = mutableList;
+final KtList<int> immutableList = mutableList.toList();
```

You will even find methods returning a `KtMutableList` for a `KtList` in this library. This is a performance optimisation and is fine because nobody is holding a reference to the mutable collection. It will never change.

https://github.com/passsy/kt.dart/blob/b0a5792c02125bc6cbe01e7c90345f76d2414933/lib/src/collection/kt_iterable.dart#L540-L549

But theoretically, one could cast it to a `KtMutableList` and do evil things. (Whoever reads this, please don't rely in internal APIs, they might change with every patch upgrade)

**Comment by mhmdanas** [comment]
After reading your comment, this does make sense! Thanks for taking the time to write such a detailed and great comment and, more importantly, such a great library!
