### ISSUE TITLE
from method fails when elements is null

### ISSUE THREAD

**Issue by kevin-haynie** [passsy/kt.dart#94]
It would be very helpful if the from factory constructor was changed to more gracefully handle when the 'elements' input parameter is null.  I've found that many times my 'elements' input value is null when reading from databases.  If I pass in a null value to the 'from' method, I get an exception.  I would much rather have an EmptyList() returned.

I suggest the following mod:

```dart
  /**
   * Returns a new read-only list based on [elements].
   */
  factory KtList.from([Iterable<T> elements = const []]) {
    if (elements == null || elements.isEmpty) return EmptyList();
    return DartList(elements);
  }
```

**Comment by passsy** [comment]
Thanks for reporting this. The API wasn't clear that `null` is not supported. This has been fixed in #95. All `from` constructors are now annotated with `@nonNull`.

ktdart expects all inputs to be non-nullable, unless explicitly stated otherwise. This is in preparation for non-nullable types in dart (https://github.com/dart-lang/language/issues/110). Once they landed you will never run into such problems again.

For now, if you're in doubt, use:

```dart
KtList.from(row ?? []);
```
